[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "ase-gxtb"
version = "0.1.0"
description = "ASE calculator wrapper for the GxTB semiempirical binary"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
keywords = ["ase", "gxtb", "xtb", "semiempirical", "calculator", "computational-chemistry"]
dependencies = [
    "ase==3.28.0",
    "numpy==2.0.2",
]

[project.scripts]
gxtb-install = "ase_gxtb.binary:cli_install"

[project.urls]
Source = "https://https://github.com/doublelayer/GxTB-wrapper"

[tool.setuptools.packages.find]
where = ["src"]
